[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pa2579-student-risk"
version = "0.1.13"
description = "Decision Tree pipeline for student performance risk prediction"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "PA2579 Ilie" }
]
dynamic = ["dependencies"]

[project.scripts]
pa2579-preprocess = "src.preprocess:preprocess"
pa2579-train = "src.train:train"
pa2579-evaluate = "src.evaluate:evaluate_pipeline"
pa2579-api = "src.api:run"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
